---
stages:
- name: BUILD
  inputs:
  - type: git
    branch: master
    service: ${SAMPLE_REPO}
  triggers:
  - type: commit
  jobs:
  - name: Build
    type: buider
    script: |
    #!/bin/bash
    # The default Node.js version is 0.10.40
    # To use Node.js 0.10.48, uncomment the following line:
    #export PATH=/opt/IBM/node-v0.10.48/bin:$PATH
    # To use Node.js 0.12.7, uncomment the following line:
    #export PATH=/opt/IBM/node-v0.12/bin:$PATH
    # To use Node.js 4.4.5, uncomment the following line:
    #export PATH=/opt/IBM/node-v4.4.5/bin:$PATH
    # To use Node.js 6.7.0, uncomment the following line:
    #export PATH=/opt/IBM/node-v6.7.0/bin:$PATH
    npm install
- name: DEPLOY
  inputs:
  - type: job
    stage: BUILD
    job: Build
  triggers:
  - type: stage
  properties:
  - name: WATSON_ASSISTANT_USERNAME
    value: ${WATSON_ASSISTANT_USERNAME}
    type: text
  - name: WATSON_ASSISTANT_PASSWORD
    value: ${WATSON_ASSISTANT_PASSWORD}
    type: text
  - name: WATSON_ASSISTANT_VERSION
    value: ${WATSON_ASSISTANT_VERSION}
    type: text
  - name: WATSON_ASSISTANT_WORKSPACE
    value: ${WATSON_ASSISTANT_WORKSPACE}
    type: text
  - name: CLOUDANT_USERNAME
    value: ${CLOUDANT_USERNAME}
    type: text
  - name: CLOUDANT_PASSWORD
    value: ${CLOUDANT_PASSWORD}
    type: text
  - name: CLOUDANT_HOST
    value: ${CLOUDANT_HOST}
    type: text
  - name: CLOUDANT_URL
    value: ${CLOUDANT_URL}
    type: text
  - name: DATABASE_NAME
    value: ${DATABASE_NAME}
    type: text
  - name: TELEGRAM_KEY
    value: ${TELEGRAM_KEY}
    type: text
  - name: STT_PASSWORD
    value: ${STT_PASSWORD}
    type: text
  - name: TTS_PASSWORD
    value: ${TTS_PASSWORD}
    type: text
  - name: STT_USERNAME
    value: ${STT_USERNAME}
    type: text
  - name: STT_PASSWORD
    value: ${STT_PASSWORD}
    type: text
  jobs:
  - name: Blue-Green Deploy
    type: deployer
    target:
      region_id: ${PROD_REGION_ID}
      organization: ${PROD_ORG_NAME}
      space: ${PROD_SPACE_NAME}
      application: ${CF_APP_NAME}
    script: |
      #!/bin/bash
      # Push app
      if ! cf app $CF_APP; then  
        cf push $CF_APP
      else
        OLD_CF_APP=${CF_APP}-OLD-$(date +"%s")
        rollback() {
          set +e  
          if cf app $OLD_CF_APP; then
            cf logs $CF_APP --recent
            cf delete $CF_APP -f
            cf rename $OLD_CF_APP $CF_APP
          fi
          exit 1
        }
        set -e
        trap rollback ERR
        cf rename $CF_APP $OLD_CF_APP
        cf push $CF_APP
        cf delete $OLD_CF_APP -f
      fi
      #Print the dev test variabel
      # Export app name and URL for use in later Pipeline jobs
      export CF_APP_NAME="$CF_APP"
      export APP_URL=http://$(cf app $CF_APP_NAME | grep -e urls: -e routes: | awk '{print $2}')
      # View logs
      #cf logs "${CF_APP}" --recent
      
